# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Vishal Green
title: Student and Software Engineer Intern
email: vgreen_7@yahoo.com
website: https://vgreen7.github.io/resume/

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: vgreen_04
github_username:  vgreen7
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: v.green_04
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: Vishal Green
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
  #icon: fas fa-globe
  #url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
gtag: "G-WW4P8T9DQJ"
# google_analytics: G-WW4P8T9DQJ

# ga_tracking: G-WW4P8T9DQJ
# ga_tracking_anonymize_ip: true

# About Section
# about_title: About Me
about_profile_image: images/profile.jpeg
about_content: | # this will include new lines to allow paragraphs

  I have a broad range of technical skills including video editing, photoshop image editing, Google Search Engine Optimization, social media management, website development, and software development. I am familiar with HTML and CSS,  as well as the Lua scripting language. I have basic experience with Java, JavaScript, and Python.

  I am a great people person, always eager to engage with and work with others. This plays into my leadership ability and ability to work with others.

 # I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Wonderful World Studios LLC
        link: wonderfulworldstudios.com
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            # icon: fab fa-github
            # url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Changing the way people view gaming...
        description: | # this will include new lines to allow paragraphs
          I am currently developing a video game app and I manage a team of 3 associates. I am using the Defold engine and coding in Lua.
      
      - layout: top-middle
        title: Passion Project
        description: |
          For my school passion project, I worked with a team of 2 others to develop an 8 week curriculum targeted for 6th grade students to teach them the basics of coding using scrath. After developing the curriculum, we executing it by working with a 6th grade class once a week for 8 weeks.         
          

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: EastBanc Technologies
        link: https://eastbanctech.com/
        # link_text: boringcompany.com
        sub_title: Engineering Intern
        caption: June 2021 - Present
        description: | # this will include new lines to allow paragraphs
            I worked with a team of interns in the development of the [SNOWiQ](https://docs.snowiq.net/) documentation site, a site containing documentation for SNOWiQ, a snowplow fleet mapping app.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: West Springfield High School
        caption: 2019 - Present
        #sub_title: BSc Computer Science
        #quote: >
         # Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        #description: | # this will include new lines to allow paragraphs
        #  During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

        #  I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in technology and software development, some of my other interests and hobbies are:
      - Baseball
      - Running Track
      - Gaming
      - Photography

      

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
